### ISSUE TITLE
pycortecs docs

### ISSUE THREAD

**Issue by markoarnauto** [cortecs-ai/cortecs-py#3]
- [x] basic readme example 
- [x] show case #1 
- [ ] show scheduling using python appscheduler
- [x] show case high throughput (summarization) 
- [x] show low-latency, high requests (reddit stream processing)

**Comment by eva-jagodic** [comment]
Leftover tasks:
- show scheduling using python appscheduler - not high priority right now, will come back to this later
- bar chart - the last decision was to show price and max. throughput and compare with groq and together, but we this is also not very favorable to us/doesn't clearly show our benefits -> we are better in price but worse in throughput than together (together boasts 2M tokens per minute throughput), and better in throughput but worse in price than groq

**Comment by eva-jagodic** [comment]
Bar chart added, python appschduler separated to new issue: #10
